language: python
python: 3.4
before_install:
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_e69c6696ca91_key -iv $encrypted_e69c6696ca91_iv -in publish-key.enc -out ~/.ssh/publish-key -d
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
  - find
  - chmod u=rw,og= ~/.ssh/publish-key
  - git --version
  - git remote set-url origin git@github.com:pytest-dev/blog.pytest.org.git
  - git fetch origin -f gh-pages:gh-pages

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  - make publish
